project_id = "pgaaycstrvjylnamngew"

[functions.analyze-landing-page]
verify_jwt = false

[functions.extract-sitemap]
verify_jwt = false

[functions.regenerate-ad-copy]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.analysis-chat-assistant]
verify_jwt = false
